version: '3.8'

networks:
  backend:

services:
  authenticate:
    container_name: auth
    image: dotnet-auth:0.12
    environment:
      - DB_HOST=mssql
      - DB_PORT=1433
      - DB_NAME=AuthenticateDB
      - DB_SA_PASSWORD=Admin@123
      - DB_USER=sa
      - ASPNETCORE_ENVIRONMENT=Development
      # - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
    ports:
      - "5280:5280"
    networks:
      - backend
    depends_on:
      - mssql    

  mssql:
    container_name: sql
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin@123
    ports:
      - "1433:1433"
    networks:
      - backend