# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  authenticate:
    image: authenticate
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5280:5280
